BrightSkool/Models/SidebarModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BrightSkool.Model
{
    public class SidebarModel
    {
        public string CurrentPage { get; set; }
    }
}

BrightSkool/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BrightSkool.Controllers
{
    public class AccountController : Controller
    {
        // GET: Account
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        public ActionResult Login()
        {
            return RedirectToAction("ProcessRegistration", "Registration");
        }
    }
}

BrightSkool/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BrightSkool.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }
}

BrightSkool/Controllers/LayoutController.cs
using BrightSkool.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BrightSkool.Controllers
{
    public class LayoutController : Controller
    {
        [ChildActionOnly]
        public PartialViewResult Header()
        {
            return PartialView("_Header");
        }

        [ChildActionOnly]
        public PartialViewResult Footer()
        {
            return PartialView("_Footer");
        }

        [ChildActionOnly]
        public PartialViewResult Sidebar(string currentPage)
        {
            var sidebarModel = new SidebarModel
            {
                CurrentPage = currentPage
            };

            return PartialView("_Sidebar", sidebarModel);
        }
    }
}

BrightSkool/Controllers/MasterController.cs
using BrightSkool.BusinessLayer.BAL.Masters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BrightSkool.Controllers
{
    public class MasterController : Controller
    {
        ICountryService _countryService;
        ICurrencyService _currencyService;
        ILanguageService _languageService;
        IReligionService _religionService;
        IRaceService _raceService;
        INationalityService _nationalityService;
        IRelationshipService _relationshipService;

        public MasterController(ICountryService countryService, ICurrencyService currencyService, ILanguageService languageService, IReligionService religionService, IRaceService raceService, INationalityService nationalityService, IRelationshipService relationshipService)
        {
            _countryService = countryService;
            _currencyService = currencyService;
            _languageService = languageService;
            _religionService = religionService;
            _raceService = raceService;
            _nationalityService = nationalityService;
            _relationshipService = relationshipService;
        }
        public async Task<ActionResult> Countries()
        {
            var countryResult = await _countryService.GetCountries();

            return View(countryResult);
        }

        public async Task<ActionResult> Currencies()
        {
            var currencyResult = await _currencyService.GetCurrencies();

            return View(currencyResult);
        }

        public async Task<ActionResult> Languages()
        {
            var languageResult = await _languageService.GetLanguages();

            return View(languageResult);
        }

        public async Task<ActionResult> Religions()
        {
            var religionResult = await _religionService.GetReligions();

            return View(religionResult);
        }

        public async Task<ActionResult> Races()
        {
            var raceResult = await _raceService.GetRace();

            return View(raceResult);
        }

        public async Task<ActionResult> Nationalities()
        {
            var nationalityResult = await _nationalityService.GetNationalities();

            return View(nationalityResult);
        }

        public async Task<ActionResult> Relationships()
        {
            var relationShipResult = await _relationshipService.GetRelationships();

            return View(relationShipResult);
        }
    }
}

BrightSkool/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BrightSkool/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BrightSkool/Views/Home/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <link href="~/Content/fonts-open-sans.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/fonts-ptsans-narrow.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/fonts-sourcesans-pro.css" rel="stylesheet" type="text/css" />

    @Styles.Render("~/Bundles/Frontend/libs/css")
    @RenderSection("Styles", false)
    @Styles.Render("~/Bundles/Frontend/metronic/css")
    @Styles.Render("~/Views/Home/layout.css")
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body class="corporate">
    <div class="pre-header">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-6 additional-shop-info">
                    <ul class="list-unstyled list-inline">
                        <li><i class="fa fa-phone"></i><span>+65 6272 7303</span></li>
                        <li><i class="fa fa-envelope-o"></i><span>info@brightskool.com</span></li>
                    </ul>
                </div>
                <div class="col-md-6 col-sm-6 additional-nav">
                    <ul class="list-unstyled list-inline pull-right">
                        <li>
                            <a href="#">Admission Enquiry</a>
                        </li>
                        <li>
                            <a href="/Registration/Registration">Registration</a>
                        </li>
                        <li>
                            <a href="/Account/Login">Log in</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="header">
        <div class="container">
            <a class="site-logo" href="/">
                <img src="~/App_Images/Logo/app-logo.png" alt="" width="168" height="33">
            </a>
            <a href="javascript:void(0);" class="mobi-toggler"><i class="fa fa-bars"></i></a>
            <div class="header-navigation pull-right font-transform-inherit">
                <ul>
                    <li class="">
                        <a href="/">Home page</a>
                    </li>
                    <li class="">
                        <a href="#">About us</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="main">
        <div class="container">
            @RenderBody()
        </div>
    </div>
    <div class="footer">
        <div class="container">
            <div class="row">
                <!-- BEGIN COPYRIGHT -->
                <div class="col-md-6 col-sm-6 padding-top-10">
                    2016 © BrightSword Technologies. ALL Rights Reserved. <a href="javascript:;">Privacy Policy</a> | <a href="javascript:;">Terms of Service</a>
                </div>
                <!-- END COPYRIGHT -->
                <!-- BEGIN PAYMENTS -->
                <div class="col-md-6 col-sm-6">
                    <ul class="social-footer list-unstyled list-inline pull-right">
                        <li><a href="javascript:;"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="javascript:;"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="javascript:;"><i class="fa fa-dribbble"></i></a></li>
                        <li><a href="javascript:;"><i class="fa fa-linkedin"></i></a></li>
                        <li><a href="javascript:;"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="javascript:;"><i class="fa fa-skype"></i></a></li>
                        <li><a href="javascript:;"><i class="fa fa-github"></i></a></li>
                        <li><a href="javascript:;"><i class="fa fa-youtube"></i></a></li>
                        <li><a href="javascript:;"><i class="fa fa-dropbox"></i></a></li>
                    </ul>
                </div>
                <!-- END PAYMENTS -->
            </div>
        </div>
    </div>
    @Scripts.Render("~/Bundles/Frontend/libs/js")
    @Scripts.Render("~/Bundles/Frontend/metronic/js")
    @RenderSection("Scripts", false)
</body>
</html>

BrightSkool/Views/Layout/_Footer.cshtml
@{
    Layout = null;
}
<div class="page-footer-inner">
    <span class="text-muted">
        <small>
            2016 © <a href="http://brightskool.com/" target="_blank">BrightSkool</a> By<a href="http://brightsword.com/" target='_blank'> BrightSword.</a>            
        </small>
    </span>
</div>
<div class="scroll-to-top">
    <i class="icon-arrow-up"></i>
</div>

BrightSkool/Views/Layout/_Header.cshtml
@{
    Layout = null;
}
<div class="page-header-inner">
    <div class="page-logo">
        <a href="@Url.Action("Index", "Home", new {area = string.Empty})" target="_blank">
            <img src="~/App_Images/Logo/bishopcottonlogo.png" alt="logo" class="logo-default" width="149" height="72" />
        </a>
        <div class="menu-toggler sidebar-toggler">
            <!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
        </div>
    </div>
    <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
    </a>
    <div class="page-top">
        <div class="top-menu">
            <ul class="nav navbar-nav pull-right">
                <!-- BEGIN NOTIFICATION DROPDOWN -->
                <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                <li class="dropdown dropdown-extended dropdown-notification dropdown-dark" id="header_notification_bar">
                    <a href="javascript:;" class="dropdown-toggle hover-initialized" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                        <i class="icon-bell"></i>
                        <!-- ngIf: vm.unreadNotificationCount --><span class="badge badge-danger ng-binding ng-scope"> 1 </span><!-- end ngIf: vm.unreadNotificationCount -->
                    </a>
                    <ul class="dropdown-menu" id="UserNotificationDropdown">
                        <li class="external notifications-header">
                            <div class="text-left">
                                <!-- ngIf: vm.unreadNotificationCount --><a href="" class="ng-scope">Set all as read</a><!-- end ngIf: vm.unreadNotificationCount ng-click="vm.setAllNotificationsAsRead(); $event.preventDefault(); $event.stopPropagation();" ng-if="vm.unreadNotificationCount" -->
                                <a class="pull-right" href="">Settings</a> @*ng-click="vm.openNotificationSettingsModal()"*@
                            </div>
                        </li>
                        <li>
                            <!-- ngRepeat: notification in vm.notifications --><ul class="dropdown-menu-list ng-scope"> @*ng-repeat="notification in vm.notifications"*@
                                <li>
                                    <a href="" class="user-notification-item user-notification-item-unread"> <!--ng-class="{'user-notification-item-unread': notification.state=='UNREAD', 'user-notification-item-clickable': notification.url}"-->>
                                        <span class="details ng-binding">
                                            <i class="fa fa-check"></i> Welcome to BrightSkool! Notification system is used to inform you for intended events. You ca...
                                        </span>
                                        <div>
                                            <span class="notification-time" title="2016-05-13 07:46:59" am-time-ago="notification.time">2 months ago</span>
                                            <!-- ngIf: notification.state=='UNREAD' --><span class="ng-scope"> - <span class="set-as-read-text">set as read</span></span><!-- end ngIf: notification.state=='UNREAD' ng-if="notification.state=='UNREAD'" ng-click="vm.setNotificationAsRead(notification); $event.preventDefault(); $event.stopPropagation();" -->
                                        </div>
                                    </a>
                                </li>
                            </ul><!-- end ngRepeat: notification in vm.notifications -->
                            <!-- ngIf: !vm.notifications.length -->
                        </li>
                        <!-- ngIf: vm.notifications.length -->
                        <li class="external notifications-footer ng-scope">  @*ng-if="vm.notifications.length"*@
                            <div class="text-center"><a ui-sref="notifications" href="#/notifications">See all notifications</a></div>
                        </li><!-- end ngIf: vm.notifications.length -->
                    </ul>
                </li>
                <!-- END NOTIFICATION DROPDOWN -->
                <li class="separator hide"> </li>

                <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                <li class="dropdown dropdown-user dropdown-dark">
                    <a href="#" class="dropdown-toggle hover-initialized" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" title="">
                        <span class="username username-hide-on-mobile ng-binding">
                            <!-- ngIf: vm.isImpersonatedLogin --> Administrator
                        </span>
                        <img id="HeaderProfilePicture" alt="" class="img-circle" src="~/App_Images/ProfilePic/default-profile-picture.png">
                    </a>
                    <ul class="dropdown-menu dropdown-menu-default">
                        <!-- ngIf: vm.isImpersonatedLogin -->
                        <!-- ngIf: vm.isImpersonatedLogin -->
                        <li class="dropdown-submenu">
                            <a class="open-left" href=""><i class="icon-link"></i> Linked accounts</a>
                            <ul class="dropdown-menu" style="display: none;">
                                <!-- ngRepeat: linkedUser in vm.recentlyUsedLinkedUsers -->
                                <!-- ngIf: vm.recentlyUsedLinkedUsers.length > 0 -->
                                <li>
                                    <a href=""> @*ng-click="vm.manageLinkedAccounts()"*@
                                        <i class="icon-settings"></i> Manage accounts
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href=""><i class="icon-key"></i> Change password</a> @*ng-click="vm.changePassword()"*@
                        </li>
                        <li>
                            <a href=""><i class="icon-shield"></i> Login attempts</a>  @*ng-click="vm.showLoginAttempts()"*@
                        </li>
                        <li>
                            <a href=""><i class="icon-user"></i> Change profile picture</a> @*ng-click="vm.changePicture()"*@
                        </li>
                        <li>
                            <a href=""><i class="icon-settings"></i> My settings</a> @*ng-click="vm.editMySettings()"*@
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="/Account/Logout"><i class="icon-logout"></i> Logout</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>

BrightSkool/Views/Layout/_Sidebar.cshtml
@model BrightSkool.Model.SidebarModel
<div class="page-sidebar navbar-collapse collapse">
    <ul class="page-sidebar-menu" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
        <li class="start @(Model.CurrentPage.Equals(PageNames.Dashboard)?"active":"")">
            <a href="#">
                <i class="icon-home"></i>
                <span class="title">Dashboard</span>
            </a>
        </li>
        <li class="@(Model.CurrentPage.Contains(PageNames.Admission)?"active open":"")">
            <a href="#">
                <i class="icon-users"></i>
                <span class="title">Admission</span>
                <span class="arrow @(Model.CurrentPage.Contains(PageNames.Admission)?"open":"")"></span>
            </a>
            <ul class="sub-menu">
                <li class="@(Model.CurrentPage.Equals(PageNames.Admission_Enquiries)?"active":"")">
                    <a href="/Admission/Index">
                        <i class="icon-call-in"></i>
                        <span class="title">Admission Enquiries</span>
                    </a>
                </li>
                <li class="@(Model.CurrentPage.Equals(PageNames.Admission_RegisteredStudents)?"active":"")">
                    <a href="/Registration/ProcessRegistration">
                        <i class="icon-action-redo"></i>
                        <span class="title">Registered Students</span>
                    </a>
                </li>
            </ul>
        </li>

        <li class="@(Model.CurrentPage.Contains(PageNames.SchoolSettings)?"active open":"")">
            <a href="/SchoolProfile/Index">
                <i class="icon-settings"></i>
                <span class="title">School Settings</span>
                <span class="arrow @(Model.CurrentPage.Contains(PageNames.SchoolSettings)?"open":"")"></span>
            </a>
            <ul class="sub-menu">
                <li class="@(Model.CurrentPage.Equals(PageNames.SchoolSettings_Profile)?"active":"")">
                    <a href="/SchoolProfile/ReadModel">
                        <span><i class="sub-menu-icon icon-graduation"></i> School Profile</span>
                    </a>
                </li>
            </ul>
        </li>
        <li class="@(Model.CurrentPage.Contains(PageNames.Settings)?"active open":"")">
            <a href="#">
                <i class="icon-settings"></i>
                <span class="title">App Settings</span>
                <span class="arrow @(Model.CurrentPage.Contains(PageNames.Settings)?"open":"")"></span>
            </a>
            <ul class="sub-menu">
                <li class="@(Model.CurrentPage.Equals(PageNames.Settings_Country)?"active":"")">
                    <a href="/Master/Countries">
                        <span><i class="sub-menu-icon icon-globe"></i> Countries</span>
                    </a>
                </li>
                <li class="@(Model.CurrentPage.Equals(PageNames.Settings_Currency)?"active":"")">
                    <a href="/Master/Currencies">
                        <span><i class="sub-menu-icon icon-wallet"></i> Currencies</span>
                    </a>
                </li>
                <li class="@(Model.CurrentPage.Equals(PageNames.Settings_Language)?"active":"")">
                    <a href="/Master/Languages">
                        <span><i class="sub-menu-icon icon-flag"></i> Languages</span>
                    </a>
                </li>
                <li class="@(Model.CurrentPage.Equals(PageNames.Settings_Religion)?"active":"")">
                    <a href="/Master/Religions">
                        <span><i class="sub-menu-icon icon-info"></i> Religions</span>
                    </a>
                </li>
                <li class="@(Model.CurrentPage.Equals(PageNames.Settings_Race)?"active":"")">
                    <a href="/Master/Races">
                        <span><i class="sub-menu-icon icon-paper-clip"></i> Races</span>
                    </a>
                </li>
                <li class="@(Model.CurrentPage.Equals(PageNames.Settings_Nationality)?"active":"")">
                    <a href="/Master/Nationalities">
                        <span><i class="sub-menu-icon icon-paper-clip"></i> Nationalities</span>
                    </a>
                </li>
                <li class="@(Model.CurrentPage.Equals(PageNames.Settings_Relationship)?"active":"")">
                    <a href="/Master/Relationships">
                        <span><i class="sub-menu-icon icon-paper-clip"></i> Relationships</span>
                    </a>
                </li>
            </ul>
        </li>
        @*<li class="@(Model.CurrentPage.Contains(PageNames.Administration)?"active open":"")">
                <a href="javascript:;" class="auto">
                    <i class="icon-settings"></i>
                    <span class="title">Administration</span>
                    <span class="arrow @(Model.CurrentPage.Contains(PageNames.Administration)?"open":"")"></span>
                </a>
                <ul class="sub-menu">
                    <li class="@(Model.CurrentPage.Equals(PageNames.Administration_Roles)?"active":"")">
                        <a href="/Roles/Index">
                            <span><i class="sub-menu-icon icon-briefcase"></i> Roles</span>
                        </a>
                    </li>
                    <li class="@(Model.CurrentPage.Equals(PageNames.Administration_Users)?"active":"")">
                        <a href="/Mpa/Users">
                            <span><i class="sub-menu-icon icon-users"></i> Users</span>
                        </a>
                    </li>
                </ul>
            </li>*@
    </ul>
</div>

BrightSkool/Views/Master/Countries.cshtml
@model List<BrightSkool.Domain.Models.CommonModel.Country>
@{
    ViewBag.CurrentPage = "AppSettings.Country";
}
<ul class="page-breadcrumb breadcrumb">
    <li>
        <a href="/Dashboard/Index">Home</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <span class="active">Countries</span>
    </li>
</ul>

<div class="portlet light bordered">
    <div class="portlet-title">
        <div class="caption font-blue-madison">
            <i class="icon-info font-blue-madison"></i>
            <span class="caption-subject bold uppercase">Countries</span>
        </div>
    </div>
    <div class="portlet-body">
        <table class="table table-striped table-bordered table-hover order-column dataTable no-footer" id="tblcountries">
            <thead>
                <tr>
                    <th>Country Code</th>
                    <th>Country Name</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var country in Model)
                {
                    <tr>
                        <td>@country.CountryCode</td>
                        <td>@country.CountryName</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@Styles.Render(StylePaths.JQuery_datatablescss)
@Styles.Render(StylePaths.JQuery_datatables_bootstrap_css)
@Scripts.Render(ScriptPaths.JQuery_datatablesjs)
@Scripts.Render(ScriptPaths.JQuery_datatables_bootstrap_js)
@Scripts.Render(ScriptPaths.App_Masters)

BrightSkool/Views/Master/Currencies.cshtml
@model List<BrightSkool.Domain.Models.CommonModel.Currency>
@{
    ViewBag.CurrentPage = "AppSettings.Currency";
}
<ul class="page-breadcrumb breadcrumb">
    <li>
        <a href="/Dashboard/Index">Home</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <span class="active">Currencies</span>
    </li>
</ul>

<div class="portlet light bordered">
    <div class="portlet-title">
        <div class="caption font-blue-madison">
            <i class="icon-info font-blue-madison"></i>
            <span class="caption-subject bold uppercase">Currencies</span>
        </div>
    </div>
    <div class="portlet-body">
        <table class="table table-striped table-bordered table-hover order-column dataTable no-footer" id="tblcurrencies">
            <thead>
                <tr>
                    <th>Country Name</th>
                    <th>Currency Code</th>
                    <th>Currency Name</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var currency in Model)
                {
                    <tr>
                        <td>@currency.CountryName</td>
                        <td>@currency.CurrencyCode</td>
                        <td>@currency.CurrencyName</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@Styles.Render(StylePaths.JQuery_datatablescss)
@Styles.Render(StylePaths.JQuery_datatables_bootstrap_css)
@Scripts.Render(ScriptPaths.JQuery_datatablesjs)
@Scripts.Render(ScriptPaths.JQuery_datatables_bootstrap_js)
@Scripts.Render(ScriptPaths.App_Masters)

BrightSkool/Views/Master/Languages.cshtml
@model List<BrightSkool.Domain.Models.CommonModel.Language>
@{
    ViewBag.CurrentPage = "AppSettings.Language";
}
<ul class="page-breadcrumb breadcrumb">
    <li>
        <a href="/Dashboard/Index">Home</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <span class="active">Languages</span>
    </li>
</ul>

<div class="portlet light bordered">
    <div class="portlet-title">
        <div class="caption font-blue-madison">
            <i class="icon-info font-blue-madison"></i>
            <span class="caption-subject bold uppercase">Languages</span>
        </div>
    </div>
    <div class="portlet-body">
        <table class="table table-striped table-bordered table-hover order-column dataTable no-footer" id="tbllanguages">
            <thead>
                <tr>
                    <th>Language Code</th>
                    <th>Language Name</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var language in Model)
                {
                    <tr>
                        <td>@language.LangaugeCode</td>
                        <td>@language.LanguageName</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@Styles.Render(StylePaths.JQuery_datatablescss)
@Styles.Render(StylePaths.JQuery_datatables_bootstrap_css)
@Scripts.Render(ScriptPaths.JQuery_datatablesjs)
@Scripts.Render(ScriptPaths.JQuery_datatables_bootstrap_js)
@Scripts.Render(ScriptPaths.App_Masters)

BrightSkool/Views/Master/Nationalities.cshtml
@model List<BrightSkool.Domain.Models.CommonModel.Nationality>
@{
    ViewBag.CurrentPage = "AppSettings.Nationality";
}
<ul class="page-breadcrumb breadcrumb">
    <li>
        <a href="/Dashboard/Index">Home</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <span class="active">Nationalities</span>
    </li>
</ul>

<div class="portlet light bordered">
    <div class="portlet-title">
        <div class="caption font-blue-madison">
            <i class="icon-info font-blue-madison"></i>
            <span class="caption-subject bold uppercase">Nationalities</span>
        </div>
    </div>
    <div class="portlet-body">
        <table class="table table-striped table-bordered table-hover order-column dataTable no-footer" id="tblnationalities">
            <thead>
                <tr>
                    <th>Nationality ISO</th>
                    <th>Nationality Name</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var nationality in Model)
                {
                    <tr>
                        <td>@nationality.CountryNationality</td>
                        <td>@nationality.ISONationality</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@Styles.Render(StylePaths.JQuery_datatablescss)
@Styles.Render(StylePaths.JQuery_datatables_bootstrap_css)
@Scripts.Render(ScriptPaths.JQuery_datatablesjs)
@Scripts.Render(ScriptPaths.JQuery_datatables_bootstrap_js)
@Scripts.Render(ScriptPaths.App_Masters)

BrightSkool/Views/Shared/DisplayTemplates/Email.cshtml
@model BrightSkool.Domain.Models.CommonModel.Email
<div class="col-md-4">
    <div class="form-group form-md-line-input form-md-floating-label">
        <label class="form-control @(Model.EmailAddress==null?"":"edited")" name="EmailAddress">@Model.EmailAddress</label>
        <label>Email</label>
    </div>
</div>

BrightSkool/Views/Shared/DisplayTemplates/Fax.cshtml
@model BrightSkool.Domain.Models.CommonModel.Phone
<div class="col-md-4">
    <div class="form-group form-md-line-input form-md-floating-label">
        <label class="form-control @(Model.PhoneNumber==null?"":"edited")" name="PhoneNumber">@Model.PhoneNumber</label>
        <label>Fax Number</label>
    </div>
</div>

BrightSkool/Views/Shared/DisplayTemplates/Phone.cshtml
@model BrightSkool.Domain.Models.CommonModel.Phone

<div class="col-md-4">
    <div class="form-group form-md-line-input form-md-floating-label">
        <label class="form-control @(Model.PhoneNumber==null?"":"edited")" name="PhoneNumber">@Model.PhoneNumber</label>
        <label>Phone Number </label>
    </div>
</div>

BrightSkool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js" data-ng-app="app"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js" data-ng-app="app"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    <title>BrightSkool</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <link rel="shortcut icon" href="~/favicon.ico" />

    @*Style Sheets*@

    <link href="~/Content/fonts-open-sans.css" rel="stylesheet" type="text/css" />
    @Styles.Render("~/Bundles/app/libs/css")
    @Styles.Render("~/Bundles/app/metronic/css")

    @*Jquery Scripts*@

    @Scripts.Render("~/Bundles/Frontend/libs/js")
    @Scripts.Render("~/Bundles/app/metronic/js")
    @*@Scripts.Render("~/Bundles/Common/js")*@
</head>

<body class="page-md page-header-fixed page-sidebar-closed-hide-logo">
    <div class="page-header navbar navbar-fixed-top md-shadow-zero-light">
        @Html.Action("Header", "Layout")
    </div>
    <div class="page-container">
        <div class="page-sidebar-wrapper">
            @Html.Action("Sidebar", "Layout", new { currentPage = ViewBag.CurrentPage })
        </div>
        <div class="page-content-wrapper">
            <div class="page-content">
                @RenderBody()
            </div>
        </div>
    </div>

    <div class="page-footer">
        @Html.Action("Footer", "Layout")
    </div>
</body>
</html>